---
dist: trusty
sudo: false
language: php

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - DB_HOST=localhost
    - DB_USER=travis
    - DB_PASSWORD=DB_NAME=2moons
    - ADMIN_NAME=admin
    - ADMIN_PASSWORD=admin
    - ADMIN_MAIL=mail@example.com

php:
  - '7.0'

matrix:
  fast_finish: true

install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS 2moons;'  -uroot
  - php -S 0.0.0.0:8000
# - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8000s &
  - composer install

before_script:
  # Start a web server on port 8888, run in the background; wait for
  # initialization.
  - nohup php -S localhost:8888 > /dev/null 2>&1 &

script:
  - '! find . -type f -name "*.php" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"'